start-at-login = false
after-startup-command = [
    'exec-and-forget /opt/homebrew/bin/borders active_color=0xff965ce4 inactive_color=0x00000000 width=5.0 hidpi=on',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 24
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 6
inner.vertical = 6
outer.left = 6
outer.bottom = 6
outer.top = 6
outer.right = 6

[mode.main.binding]
ctrl-cmd-1 = 'workspace 1'
ctrl-cmd-2 = 'workspace 2'
ctrl-cmd-3 = 'workspace 3'
ctrl-cmd-4 = 'workspace 4'
ctrl-cmd-5 = 'workspace 5'
ctrl-cmd-6 = 'workspace 6'
ctrl-cmd-7 = 'workspace 7'
ctrl-cmd-8 = 'workspace 8'
ctrl-cmd-9 = 'workspace 9'

ctrl-cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
ctrl-cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
ctrl-cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
ctrl-cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
ctrl-cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
ctrl-cmd-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
ctrl-cmd-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
ctrl-cmd-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

ctrl-cmd-h = 'focus left'
ctrl-cmd-j = 'focus down'
ctrl-cmd-k = 'focus up'
ctrl-cmd-l = 'focus right'
ctrl-cmd-shift-h = 'move left'
ctrl-cmd-shift-j = 'move down'
ctrl-cmd-shift-k = 'move up'
ctrl-cmd-shift-l = 'move right'
ctrl-cmd-u = 'workspace prev'
ctrl-cmd-i = 'workspace next'
ctrl-cmd-tab = 'workspace-back-and-forth'
ctrl-cmd-o = 'focus-monitor --wrap-around next'
ctrl-cmd-shift-o = 'move-node-to-monitor --wrap-around --focus-follows-window next'
ctrl-cmd-backslash = 'layout tiles horizontal'
ctrl-cmd-minus = 'layout tiles vertical'
ctrl-cmd-comma = 'layout accordion horizontal vertical'
ctrl-cmd-f = 'fullscreen'
ctrl-cmd-t = 'layout floating tiling'
ctrl-cmd-equal = 'balance-sizes'
ctrl-cmd-x = 'close'
ctrl-cmd-r = 'mode resize'
ctrl-cmd-shift-c = 'reload-config'

[mode.resize.binding]
h = 'resize width -60'
l = 'resize width +60'
j = 'resize height +60'
k = 'resize height -60'
equal = 'balance-sizes'
esc = 'mode main'
enter = 'mode main'

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'
