hunk_headers = true
line_numbers = true
menu_bar = true
mode = "auto"
theme = "death-note"
transparent_background = true
watch = true
wrap_lines = false

[themes.death-note]
accent = "#fe598f"
accentMuted = "#a03759"
addedBg = "#171d22"
addedContentBg = "#16201d"
addedSignColor = "#10c955"
background = "#09090b"
badgeAdded = "#10c955"
badgeNeutral = "#52f0db"
badgeRemoved = "#ff6a6e"
base = "github-dark-default"
border = "#a03759"
contextBg = "#09090b"
contextContentBg = "#09090b"
fileDeleted = "#ff6a6e"
fileModified = "#ffb200"
fileNew = "#10c955"
fileRenamed = "#52f0db"
fileUntracked = "#5fa5ff"
label = "Death Note"
lineNumberBg = "#09090b"
lineNumberFg = "#a0a0a0"
movedAddedBg = "#16201d"
movedRemovedBg = "#24151b"
muted = "#a0a0a0"
noteBackground = "#171923"
noteBorder = "#a03759"
noteTitleBackground = "#a03759"
noteTitleText = "#ededed"
panel = "#09090b"
panelAlt = "#171923"
removedBg = "#24151b"
removedContentBg = "#24151b"
removedSignColor = "#ff6a6e"
selectedHunk = "#471d2b"
text = "#ededed"

[themes.death-note.syntax_scopes]
comment = "#a0a0a0"
"comment.block" = "#a0a0a0"
"comment.line" = "#a0a0a0"
"constant" = "#5fa5ff"
"constant.language" = "#ffb200"
"constant.numeric" = "#ffb200"
"constant.other" = "#5fa5ff"
"entity.name.class" = "#52f0db"
"entity.name.function" = "#c674f9"
"entity.name.namespace" = "#52f0db"
"entity.name.tag.yaml" = "#5fa5ff"
"entity.name.type" = "#52f0db"
"entity.name.variable" = "#5fa5ff"
keyword = "#fe598f"
"keyword.control" = "#fe598f"
"keyword.operator" = "#fe598f"
meta = "#ededed"
"meta.module-reference" = "#52f0db"
"meta.object-literal.key" = "#5fa5ff"
punctuation = "#ededed"
"punctuation.definition.block" = "#ededed"
"punctuation.definition.comment" = "#a0a0a0"
"punctuation.definition.parameters" = "#ededed"
"punctuation.definition.string" = "#ededed"
"punctuation.separator" = "#ededed"
"punctuation.terminator" = "#ededed"
source = "#ededed"
text = "#ededed"
"storage.type" = "#fe598f"
"storage.type.boolean" = "#52f0db"
"storage.type.built-in" = "#52f0db"
"storage.type.generic" = "#52f0db"
"storage.type.numeric" = "#52f0db"
"storage.type.primitive" = "#52f0db"
"storage.type.string.go" = "#52f0db"
string = "#10c955"
"string.quoted" = "#10c955"
"string.regexp" = "#10c955"
"string.template" = "#10c955"
"support.function" = "#c674f9"
"support.type" = "#52f0db"
"support.type.property-name" = "#5fa5ff"
"support.variable" = "#5fa5ff"
variable = "#5fa5ff"
"variable.other" = "#5fa5ff"
"variable.other.constant" = "#5fa5ff"
"variable.other.object" = "#5fa5ff"
"variable.other.property" = "#5fa5ff"
"variable.other.readwrite" = "#5fa5ff"
"variable.parameter" = "#ffb200"
"variable.parameter.name.nix" = "#5fa5ff"
