hunk_headers = true
line_numbers = true
menu_bar = true
mode = "auto"
theme = "dusk-apple"
transparent_background = true
watch = true
wrap_lines = false

[themes.dusk-apple]
accent = "#c4a77d"
accentMuted = "#c4a77d"
addedBg = "#0a1d0f"
addedContentBg = "#103219"
addedSignColor = "#95e7a6"
background = "#09090b"
badgeAdded = "#95e7a6"
badgeNeutral = "#7cefd9"
badgeRemoved = "#ffc3bd"
base = "github-dark-default"
border = "#c4a77d"
contextBg = "#09090b"
contextContentBg = "#09090b"
fileDeleted = "#ffc3bd"
fileModified = "#ffcc85"
fileNew = "#95e7a6"
fileRenamed = "#7cefd9"
fileUntracked = "#a3dcfd"
label = "Dusk Apple"
lineNumberBg = "#09090b"
lineNumberFg = "#9b9690"
movedAddedBg = "#103219"
movedRemovedBg = "#431d1a"
muted = "#d9d0c6"
noteBackground = "#141416"
noteBorder = "#c4a77d"
noteTitleBackground = "#c4a77d"
noteTitleText = "#09090b"
panel = "#09090b"
panelAlt = "#141416"
removedBg = "#291210"
removedContentBg = "#431d1a"
removedSignColor = "#ffc3bd"
selectedHunk = "#28231c"
text = "#e9e4de"

[themes.dusk-apple.syntax_scopes]
comment = "#d9d0c6"
"comment.block" = "#d9d0c6"
"comment.line" = "#d9d0c6"
"constant" = "#a3e1ff"
"constant.language" = "#a3e1ff"
"constant.numeric" = "#a3e1ff"
"constant.other" = "#a3e1ff"
"entity.name.class" = "#d9cffd"
"entity.name.function" = "#7cefd9"
"entity.name.namespace" = "#d9cffd"
"entity.name.tag.yaml" = "#e3ded8"
"entity.name.type" = "#d9cffd"
"entity.name.variable" = "#e9e4de"
keyword = "#ffcc91"
"keyword.control" = "#ffcc91"
"keyword.operator" = "#d6d1cb"
meta = "#e9e4de"
"meta.module-reference" = "#d9cffd"
"meta.object-literal.key" = "#e3ded8"
punctuation = "#d6d1cb"
"punctuation.definition.block" = "#d6d1cb"
"punctuation.definition.comment" = "#d9d0c6"
"punctuation.definition.parameters" = "#d6d1cb"
"punctuation.definition.string" = "#d6d1cb"
"punctuation.separator" = "#d6d1cb"
"punctuation.terminator" = "#d6d1cb"
source = "#e9e4de"
text = "#e9e4de"
"storage.type" = "#ffcc91"
"storage.type.boolean" = "#d9cffd"
"storage.type.built-in" = "#e1dafe"
"storage.type.generic" = "#d9cffd"
"storage.type.numeric" = "#d9cffd"
"storage.type.primitive" = "#d9cffd"
"storage.type.string.go" = "#d9cffd"
string = "#c7dda3"
"string.quoted" = "#c7dda3"
"string.regexp" = "#c7dda3"
"string.template" = "#c7dda3"
"support.function" = "#7cefd9"
"support.type" = "#d9cffd"
"support.type.property-name" = "#e3ded8"
"support.variable" = "#e9e4de"
variable = "#e9e4de"
"variable.other" = "#e9e4de"
"variable.other.constant" = "#a3e1ff"
"variable.other.object" = "#e9e4de"
"variable.other.property" = "#e3ded8"
"variable.other.readwrite" = "#e9e4de"
"variable.parameter" = "#e9e4de"
"variable.parameter.name.nix" = "#e9e4de"
