[theme]
name = "terminal"

[theme.custom]
panel_bg = "#090b10"
surface0 = "#171923"
surface1 = "#281823"
surface_dim = "#090b10"
overlay0 = "#7f8395"
overlay1 = "#b8b6c3"
text = "#dedce3"
subtext0 = "#85899b"
accent = "#df5577"
mauve = "#df5577"
green = "#78a68e"
yellow = "#d5a14a"
red = "#df5577"
blue = "#8292cf"
teal = "#96af9e"
peach = "#d5a14a"
